#pragma once
#include <iostream>
#include <string>
#include <sstream>
#include <vector>
#include <variant>
#include <map>
#include <functional>
#include <filesystem>
#include <optional>
#include <unistd.h>
#include <sys/wait.h>